services:
  collata:
    container_name: collata
    build:
      dockerfile: ./dockerfile
      no_cache: true
      tags:
        - "collata:latest"
    ports:
      - '${PORT}:80'
    volumes:
     - collata-data-uploads:/app/public/uploads
     - collata-data-db:/app/database
    environment:
      - DATABASE_URL=file:/app/database/database.db
      - PORT=80
volumes:
  collata-data-uploads:
  collata-data-db: